packages:
  - admin
  - mobile
  - website

autoInstallPeers: true
minReleaseAge: 1

allowBuilds:
  '@firebase/util': true
  esbuild: true
  msgpackr-extract: false
  protobufjs: false
  sharp: false
  unrs-resolver: false
  workerd: false
