name: Mobile CD
on:
  push:
    branches:
      - main
      - develop

  workflow_dispatch:
    inputs:
      platform:
        description: Platform to build for (all/android/ios)
        type: choice
        required: true
        default: all
        options:
          - all
          - android
          - ios
      profile:
        description: EAS build profile (development/preview/production)
        type: choice
        required: true
        default: production
        options:
          - preview
          - development
          - production
      submit:
        description: Auto submit to the store? (production only)
        type: boolean
        default: false
        required: false

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  continuously-deploy:
    name: Mobile build / update
    runs-on: ubuntu-latest
    concurrency: mobile-continuous-deploy-fingerprint-${{ github.ref }}
    permissions:
      contents: read # Allow checkout
      pull-requests: write # Allow comments on PRs

    steps:
      - name: 🏗 Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: 🏗 Setup EAS
        uses: ./.github/actions/setup-eas
        with:
          expo-token: ${{ secrets.EXPO_TOKEN }}

      - name: 🏗 Test
        run: npm run test --if-present

      - name: 🏗 Make sure and fingerprint is working
        # if: ${{ !(github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main') }}
        if: ${{ !(github.ref == 'refs/heads/main') }}
        run: |
          npx expo-updates fingerprint:generate --platform android --debug

      - name: Continuously Deploy
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: expo/expo-github-action/continuous-deploy-fingerprint@main
        with:
          profile: ${{ inputs.profile || (github.ref == 'refs/heads/main' && 'production' || 'preview') }}
          branch: ${{ github.ref == 'refs/heads/main' && 'production' || 'preview' }}
          working-directory: "mobile"
          auto-submit-builds: true
          platform: ${{ inputs.platform ||  'all' }}
